# Generated by Django 4.1 on 2022-08-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo1',
            new_name='car_photo_1',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo2',
            new_name='car_photo_2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo3',
            new_name='car_photo_3',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_photo4',
            new_name='car_photo_4',
        ),
    ]
